### ISSUE TITLE
Race condition when new pipeline is created while pipeline is running

### ISSUE THREAD

**Issue by brjdev** [cgruver/okd-jenkins-pipeline#1]
It appears that the provisioning of a new pipeline can fail if a new pipeline is instantiated while one of the existing pipelines is running.  The settings.xml config map is being accessed, but the new provision from template tries to simultaneously create the config map.

One solution might be to test for the existence of the config map and then skip creation.

**Comment by brjdev** [comment]
Actually, no build need be running.  I still see this error under monitoring:

Provision call failed: configmaps "maven-settings-xml" already exists

**Comment by cgruver** [comment]
That may be as simple as changing an oc create to an oc apply.  I'll take a look.

**Comment by cgruver** [comment]
My testing was done with the command line.  `oc process.... | oc apply -f -`.  You are using the catalog.  My suspicion is that the catalog is doing the equivalent of oc create.  That's why it is failing for you.  I will pull the maven-settings config map out of the template and create it as part of the pipeline.  That will allow for additional customization anyway.

In the mean time, use the command line to as a work around.

**Comment by cgruver** [comment]
I believe this is resolved by some significant refactoring.  Documentation is updated as well.
